
server:
  port: 8083 # 端口
spring:
  application:
    name: eureka-server #项目应用名称，这个写法是取得pom文件的artifactId的值，会在Eureka中的ui显示
eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka